simulator:
  dt: 0.02 # seconds
  gravity: 9.81 # m/s^2
  render_dim: 2 # dimensions
  frame_transition_rate: 0.2
  ground:
    size: 60 # meters
    resolution: 150 # square points in total
    random: true
  targets:
    count: 1 # number of targets
    center: [0, 0, 0.8] # meters
    std: 0.1 # meters
    size: 1.0 # meters
    variation: 0.1 # meters
    nu: 3 # icosphere resolution
    path:
      radius: 20 # meters
      resolution: 10000 # points in total
  obstacles:
    count: 30 # number of obstacles
    center: [0, 0, 0] # meters
    center_std: [10,10,0] # meters
    radius: 0.5 # meters
    radius_std: 0.5 # meters
    height: 3.0 # meters
    height_std: 5 # meters
    angle_resolution: 15 # points in total in a circle
    height_resolution: 40 # points in total
    random: true
  track:
    count: 0 # number of gates in track
    radius: 12 # meters
    gate_size: 5 # meters
    gate_resolution: 17 # points per gate shape


drone:
  joystick_calib_path: C:\Users\omrijsharon\PycharmProjects\FpyV\config\frsky.json # path to joystick calibration file
  motor_test_report_path: C:\Users\omrijsharon\Downloads\2203_5_tmotors.csv # path to motor test report file
  motor_test_report_idx: 0 # index of motor in report file
  initial_position: [0, 0, 5] # meters
  initial_orientation: [0, 0, 0] # roll pitch yaw in degrees
  initial_velocity: [1, 0, 0] # m/s
  max_rates: 1000 # degrees/s
  mass: 250 # grams
  drag_coefficient: 0.12
  motors_test_filepath: "config/motors_test_params.csv"
  rates_transition_rate: 0.7 # smaller value reacts slower [0, 1]
  thrust_transition_rate: 0.5 # instant power: smaller value reacts slower [0, 1]
  trail_length: 300 # number of points in trail

camera:
  camera_angle: 75.0 #degrees - pitch angle
  position_relative_to_frame: [0.1, 0.0, 0.0] #meters
  fov: 120.0 #degrees
  resolution: [640, 480] #pixels


calculate_needed_force_orientation:
  ref_frame: 'world'
  multiplier: 20
  mode: 'level' # 'level' or 'frontarget'
  virtual_drag_coef: 0.2
  virtual_lift_coef: 0.55
  tof_effective_dist: 1.3

