simulator:
  dt: 0.033 # seconds
  gravity: 9.81 # m/s^2
  render_dim: 2 # dimensions
  ground:
    size: 60 # meters
    resolution: 150 # square points in total
    random: true
  targets:
    count: 2 # number of targets
    center: [10, 0, 0.5] # meters
    std: 0.1 # meters
    size: 1.0 # meters
    variation: 0.1 # meters
    nu: 3 # icosphere resolution
  track:
    count: 0 # number of gates in track
    radius: 12 # meters
    gate_size: 5 # meters
    gate_resolution: 17 # points per gate shape


drone:
  joystick_calib_path: C:\Users\omrijsharon\PycharmProjects\FpyV\config\frsky.json # path to joystick calibration file
  motor_test_report_path: C:\Users\omrijsharon\Downloads\2203_5_tmotors.csv # path to motor test report file
  motor_test_report_idx: 0 # index of motor in report file
  initial_position: [0, 0, 0.5] # meters
  initial_orientation: [0, 0, 0] # roll pitch yaw in degrees
  initial_velocity: [1, 0, 0] # m/s
  max_rates: 1000 # degrees/s
  mass: 750 # grams
  drag_coefficient: 0.12
  motors_test_filepath: "config/motors_test_params.csv"
  rates_transition_rate: 0.7 # smaller value reacts slower [0, 1]
  thrust_transition_rate: 0.5 # instant power: smaller value reacts slower [0, 1]
  trail_length: 300 # number of points in trail

camera:
  camera_angle: 35.0 #degrees - pitch angle
  position_relative_to_frame: [0.1, 0.0, 0.0] #meters
  fov: 120.0 #degrees
  resolution: [640, 480] #pixels


calculate_needed_force_orientation:
  ref_frame: 'world'
  multiplier: 4
  mode: 'level' # 'level' or 'frontarget'
  virtual_drag_coef: 0.5
  virtual_lift_coef: 0.1
  tof_effective_dist: 1.3

