simulator:
  fps: 60 # frames per second
  gravity: 9.81 # m/s^2
  render_dim: 2 # dimensions
  frame_transition_rate: 0.2
  ground:
    size: 60 # meters
    resolution: 50 # square points in total
    random: true
  targets:
    count: 1 # number of targets
    center: [0, 0, 3.0] # meters
    std: 0.1 # meters
    size: 1.0 # meters
    variation: 0.1 # meters
    nu: 5 # icosphere resolution
    path:
      radius: 25 # meters
      resolution: 5500 # points in total
  obstacles:
    count: 0 # number of obstacles
    center: [0, 0, 0] # meters
    center_std: [10,10,0] # meters
    radius: 2 # meters
    radius_std: 0.5 # meters
    height: 10.0 # meters
    height_std: 5 # meters
    angle_resolution: 10 # points in total in a circle
    height_resolution: 25 # points in total
    random: true
  track:
    count: 0 # number of gates in track
    radius: 12 # meters
    gate_size: 5 # meters
    gate_resolution: 17 # points per gate shape


drone:
  joystick_calib_path: C:\Users\omri_\PycharmProjects\FpyV\config\frsky.json # path to joystick calibration file
  motor_test_report_path: C:\Users\omri_\PycharmProjects\FpyV\config\t_motos_f80_motor_test.csv # path to motor test report file
  motor_test_report_idx: 0 # index of motor in report file
  initial_position: [0, 0, 5] # meters
  initial_orientation: [0, 0, 0] # roll pitch yaw in degrees
  initial_velocity: [1, 0, 0] # m/s
  max_rates: 1000 # degrees/s
  mass: 250 # grams
  drag_coefficient: 0.2
  motors_test_filepath: "config/motors_test_params.csv"
  rates_transition_rate: 0.7 # smaller value reacts slower [0, 1]
  thrust_transition_rate: 0.5 # instant power: smaller value reacts slower [0, 1]
  trail_length: 0 # number of points in trail
  keep_distance: 6 # meters
  UWB_sensor_max_range: 13 # meters
  force_multiplier_pid:
    kP: 0.1
    kI: 2.0
    kD: 0.05
    integral_clip: 100.0
    min_output: 0.05 # not in use
    max_output: 40 # not in use
    derivative_transition_rate: 0.2 # Replacing Feedforward. Smaller value reacts slower but smoother [0, 1]

camera:
  camera_angle: 25.0 #degrees - pitch angle
  position_relative_to_frame: [0.1, 0.0, 0.0] #meters
  fov: 140.0 #degrees
  resolution: [640, 480] #pixels


point_and_shoot:
  ref_frame: 'world'
  mode: 'level' # 'level' or 'frontarget'
  virtual_drag_coefficient: 0.5
  virtual_lift_coefficient: 0.1
  tof_effective_distance: 2 # meters

